version: 2
jobs:
  build:
    docker:
      - image: clojure:openjdk-11-lein-slim-buster
        auth:
          username: victorbjelkholm
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/repo
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: apt update && apt install --yes imagemagick wget unzip
      - run: (cd chromedist && ./download.sh)
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "project.clj" }}
            - v1-dependencies-
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}
      - run: lein with-profile e2e cloverage --junit --html
      - store_test_results:
          path: target/coverage
      - store_artifacts:
          path: target/coverage
      - store_artifacts:
          path: e2e/
      - store_artifacts:
          path: /tmp/instantwebsites
